platform :ios, '12.0'

target 'SportsApplication' do

  use_frameworks!

  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'YouTubePlayer'
  pod 'ReachabilitySwift'

end
